apiVersion: apps/v1
kind: Deployment
metadata:
  name: accident-logs-backend
  labels:
    app: accident-logs
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: accident-logs
      tier: backend
  template:
    metadata:
      labels:
        app: accident-logs
        tier: backend
    spec:
      containers:
      - name: accident-logs-backend
        image: accident-logs-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080 # Changed to match your PORT
        env:
        - name: PORT
          value: "8080"
        - name: PROCORE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: accident-logs-secrets
              key: PROCORE_CLIENT_ID
        - name: PROCORE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: accident-logs-secrets
              key: PROCORE_CLIENT_SECRET
        - name: PROCORE_PROJECT_ID
          value: "117922"
        - name: PROCORE_COMPANY_ID
          valueFrom:
            secretKeyRef:
              name: accident-logs-secrets
              key: PROCORE_COMPANY_ID
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
