# Build stage
FROM golang:1.24 AS builder

WORKDIR /app

# Copy go mod files before running go mod download
COPY go.mod go.sum ./
RUN go mod download

# Now copy the rest of the source
COPY . .

# Build the Go app
RUN CGO_ENABLED=0 GOOS=linux go build -o main .

# Runtime stage
FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/main .

EXPOSE 8081
CMD ["./main"]
