apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-equipment-logs-frontend
  labels:
    app: admin-equipment-logs
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-equipment-logs
      tier: frontend
  template:
    metadata:
      labels:
        app: admin-equipment-logs
        tier: frontend
    spec:
      containers:
      - name: admin-equipment-logs-frontend
        image: admin-equipment-logs-frontend:local
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        env:
        - name: BACKEND_URL
          value: "http://admin-equipment-logs-backend:8081"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
