# Build Stage
FROM golang:1.24.2 AS builder
WORKDIR /app
COPY . .
COPY .env .env
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o main .

# Run-time Stage
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/main .
COPY --from=builder /app/.env .

EXPOSE 8082
CMD ["./main"]
