# Build Stage
FROM golang:1.24.2 as buider
WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o main .

#RUN-TIME STAGE
FROM alpine:latest

WORKDIR /app
COPY --from=buider /app/main .
COPY --from=buider /app/.env .

EXPOSE 8082
CMD [ "./main" ]


