#build stage
FROM golang:1.24 as builder

WORKDIR /app

RUN go mod download
RUN CGO_ENABLE=0 GOODS=linux go build -o main .

#runtime stage

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/main .
COPY --from=builder /app/main .

EXPOSE 8081
CMD [ "./main" ]