apiVersion: v1
kind: Service
metadata:
  name: admin-equipment-logs-backend
spec:
  selector:
    app: admin-equipment-logs
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081 # Updated to match your PORT
